---
# testing 

- hosts: "{{ target }}"
  remote_user: ansible
  become: yes
  gather_facts: yes
  vars_files:
    - group_vars/all.yml
  

  tasks:

    ## Mount Disks
    - name: Mount Disks for logs, dbtemp, db
      include_role:
        name: postgresql_mount_disks
        apply:
          tags: always
      tags: full_stack,mount_disks,never


    ## Install Postgres
    - name: Install Postgres
      include_role:
        name: postgresql_install
        apply:
          tags: always
      tags: full_stack,install,never

    ## Setup Primary Postgres Instance
    - name: Setup Postgres Primary Instance
      include_role:
        name: postgresql_primary
        apply:
          tags: always
      tags: full_stack,primary,never

    ## Setup pgbadger
    - name: Install and configure pgbadger
      include_role:
        name: postgresql_pgbadger
        apply:
          tags: always
      tags: full_stack,pgbadger,never

    ## Configure Telegraf with plugins
    - name: Add telegraf config files and plugins
      include_role:
        name: postgresql_telegraf
        apply:
          tags: always
      tags: full_stack,telegraf,never


    ## Install Postgres
    - name: Install Barman
      include_role:
        name: postgresql_barman
        apply:
          tags: always
      tags: full_stack,barman,never


