---

## CREATE IMITATION MOUNT POUNTS

- name: Create a ext4 filesystem on all disks
  filesystem:
    fstype: ext4
    dev: "{{ item }}"
  with_items:
    - /dev/sdb
    - /dev/sdc
    - /dev/sdd


- name: Create directories 
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /db
    - /log
    - /dbtemp


- name: Mount db folder
  mount:
    path: /db
    src: /dev/sdb
    fstype: ext4
    state: mounted


- name: Mount log folder
  mount:
    path: /log
    src: /dev/sdc
    fstype: ext4
    state: mounted

- name: Mount dbtemp folder
  mount:
    path: /dbtemp
    src: /dev/sdd
    fstype: ext4
    state: mounted

